name: convert_vri
description: takes a VRI HTML file and produces an SQL file to import that Tipitaka book to TPR
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  html: ^0.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  convert_vri_anudipanipatha: bin/convert_vri_anudipanipatha.dart
  convert_vri_all_e_texts: bin/convert_vri_all_e_texts.dart
